- __tests__/rikaicontent.html
- src/rikaicontent.ts
>  Check if result from caretPositionFromPoint is far from cursor

- __tests__/deinflect.ts
- src/deinflect.ts
> Add き as masu stem for 来る (closes #59)

- src/data.test.ts
- src/data.ts
Hello, could you please code review it?
Thank you!
> Fixes bug #246 in which input 'クリスチーナ' was matching to entry 'クリスチアナ'.

- src/data.ts
> Recognize choonpu after dakuon/handakuon and small ゃゅょ

- _locales/zh_hans/messages.json
> update zh-hans translation

- _locales/zh_hans/messages.json
> update zh-hans translate

- changelog.md
- src/numbers.test.ts
- src/numbers.ts
see: https://github.com/birtles/rikaichamp/issues/373#issuecomment-689976608
> Refuse to (mis)convert transliterations of kanji digits

- _locales/ja/messages.json
明けましておめでとうございます。今年もよろしくお願いします！
> Fixup grammar in ja localization

- CHANGELOG.md
- src/get-text.ts
- src/numbers.test.ts
- src/numbers.ts
> Transliterate kanji digits like 昭和二〇年

- _locales/zh_hans/messages.json
I'm quite suspicious about the meaning of `doc` but sadly there's no usage example yet, so I just made it consistent with Japanese version.
> Update Chinese translation

- _locales/zh_hans/messages.json
#683 
There's no significant error in the original automatic-translated content, so what I did was generally making the text more consistent to each other and some typesetting tweaks (like adding a space between Chinese and half-width alphanumeric characters; we believe doing this will make the text look cleaner and more elegant)
> Update Simp. Chinese translation

- src/puck.ts
Reprisal of PR https://github.com/shirakaba/10ten-ja-reader/pull/15 (which got shut down due to a force push).
I've applied your suggested refactor – looks like a good cleanup (thanks!), successfully removing the conditional overwriting of the various variables and instead setting them in a unified manner.
I think the one difference is that the refactored code will handle asymmetrical left/right insets differently – the `requiredReach` is effectively symmetrical, where I think originally it had been handled asymmetrically. Nothing wrong with symmetry, though.
> feat: moon can now project into any unsafe left/right insets

- src/content.ts
- src/popup-position.ts
> Popup positioning

- _locales/zh_hans/messages.json
Did not touch the shogi strings though...
> Tweak zh-hans translation

- CHANGELOG.md
- src/content/get-cursor-position.ts
- src/content/get-text.ts
- src/utils/dom-utils.ts
- src/utils/geometry.ts
- tests/get-text.test.ts
- tests/playground.html
> feat: add support for looking up shadow DOM content on Blink/WebKit

- package.json
- src/background/flat-file.ts
- src/background/jpdict-backend.ts
- src/content/copy-text.test.ts
- src/content/copy-text.ts
- src/content/popup/words.ts
- yarn.lock
- chore: update to jpdict-idb v2
- chore: catch errors from initializing JpdictIdb
> Update to jpdict-idb v2

- CHANGELOG.md
- src/content/iframes.ts
- tests/playground-frameset-child-1.html
- tests/playground-frameset-child-2.html
- tests/playground-frameset.html
- tests/playground.html
> fix: handle frameset elements and nested iframes

- CHANGELOG.md
- manifest.json.src
> fix: add selection styles to web_accessible_resources

- CHANGELOG.md
- css/popup.css
> fix: add a scrollbar gutter to the popup

- .github/workflows/ci.yml
- knip.ts
- src/background/background-message.ts
- src/content/popup/popup.ts
- src/options/l10n.ts
- src/utils/char-range.ts
- src/utils/fetch.ts
- src/utils/request-idle-callback.ts
- src/utils/type-helpers.ts
- src/utils/ua-utils.ts
- chore: fix remaining knip issues
- chore: enable knip in CI
> enable knip

- .gitignore
- package.json
- yarn.lock
- chore(deps): update knip to 2.33.3
- chore: add cosmos-export to .gitignore
> Update knip to 2.33.3

- src/options/DictionaryLanguageSettings.tsx
- src/options/DictionaryLanguageSettingsForm.fixture.tsx
- src/options/DictionaryLanguageSettingsForm.tsx
- src/options/OptionsPage.tsx
- src/options/options.css
- src/options/options.html
- src/options/options.ts
- chore: convert dictionary language setting to Preact
- chore: convert dictionary setting styles to Tailwind
> Convert dictionary settings to Preact/Tailwind

- CHANGELOG.md
- src/options/commands.test.ts
- src/options/commands.ts
- src/options/options.ts
- fix: rework command key handling to be more forgiving
- feat: allow setting all the different keys via options
> Various fixes to command handling

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/options/KeyboardSettings.tsx
- src/options/KeyboardSettingsForm.fixture.tsx
- src/options/KeyboardSettingsForm.tsx
- src/options/ToggleKeyForm.tsx
- chore: use flexbox instead of grid for toggle key section
- feat: add button to disable toggle shortcut
> Make it possible to disable the toggle key

- CHANGELOG.md
- src/background/background.ts
- src/background/jpdict.ts
- webpack.config.js
- fix: wait for DB to initialize after waking up
- feat: enable MV3 and non-persistent event pages
> Enable MV3 and non-persistent event pages

- CHANGELOG.md
- src/background/deinflect.test.ts
- src/background/deinflect.ts
> feat: added deinflection for ございません and くださいます and friends

- .prettierrc.json
- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- scripts/release-notes/format-release-notes.js
- scripts/release-notes/format-release-notes.test.js
- scripts/zip-src.ts
- yarn.lock
- chore: sort package.json
- chore: update CONTRIBUTING.md
- chore: strip kbd tags from release notes
- chore: structure changelog
- chore: update zip-src script
> Various release tweaks

- manifest.json.src
- src/utils/bugsnag.ts
- chore: set minimum Chrome version to 100
- chore: add safari-web-extension to set of protocols to normalize
> min chrome version

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- package.json
- src/background/flat-file.ts
- yarn.lock
- chore: update @birchill/jpdict-idb to 2.2.0
- feat: add localization for new field tags
> new field tags

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- css/popup.css
- css/themes.css
- src/common/config.ts
- src/common/content-config-params.ts
- src/content/content-config.ts
- src/content/content.ts
- src/content/popup/popup.ts
- src/content/popup/words.ts
- src/options/PopupStyleForm.fixture.tsx
- src/options/PopupStyleForm.tsx
- src/options/PopupStyleSettings.tsx
- src/options/PopupThemeRadio.fixture.tsx
- src/options/PopupThemeRadio.tsx
> feat: show Bunpro deck information

- CHANGELOG.md
- src/utils/range.ts
- tests/playground.html
- tests/range.test.ts
> fix: fix slow lookup of range offsets in long text runs

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- package.json
- src/content/popup/words.ts
- yarn.lock
- chore(deps): update knip to 3.6.0
- chore(deps): update vitest, typescript, web-ext, and html-webpack-plugin
- feat: add localization and handling for rk tag
> Handle `rk` tag

- package.json
- yarn.lock
- chore(deps): update dependency react-cosmos to v6.0.0
- chore: regenerate lockfile
> Update to react cosmos 6.0.0 release

- CHANGELOG.md
- src/background/background-request.ts
- src/background/background.ts
- src/common/config.ts
- src/common/content-config-params.ts
- src/common/puck-state.ts
- src/content/content-config.ts
- src/content/content.ts
- src/content/puck.ts
> feat: persist puck state between pages

- CHANGELOG.md
- src/content/scan-text.ts
- tests/get-text.test.ts
> fix: fix looking up text with ruby transcriptions that have nested elements

- CHANGELOG.md
- package.json
- src/background/flat-file.ts
- src/background/word-match-sorting.ts
- yarn.lock
> feat: prioritize kana matches when searching with kana

- CHANGELOG.md
- src/background/word-search.ts
> fix: sort across variants

- css/popup.css
- css/themes.css
- fix: improve contrast of default theme
- fix: make font a little thicker
- fix: boost definition font size
> improve contrast

- CHANGELOG.md
- src/background/active-tab-manager.ts
- src/background/all-tab-manager.ts
- src/background/background-message.ts
- src/background/background.ts
- src/content/content.ts
> feat: update popup when the database has finished updating

- CHANGELOG.md
- README.md
- package.json
- yarn.lock
- chore: fix CI badge
- fix: don't restrict senses when matching on search-only headwords
> fix search only form matching

- CHANGELOG.md
- src/content/puck.ts
> Prevent popup from staying open when puck intersects it

- webpack.config.js
- chore: add node prefixes to imports
- chore: add comments to webpack.config.js
- chore: tidy up getExtConfig
- chore: move bugsnag plugin configuration into getExtConfig
- chore: merge commonExtConfig into getExtConfig
- chore: inline extension target configs
> tidy up webpack config

- CHANGELOG.md
- src/content/numbers.test.ts
- src/content/numbers.ts
> fix: correctly interpret digits followed by multiple powers of ten

- CHANGELOG.md
- src/content/content.ts
- src/content/get-cursor-position.ts
- src/content/popup/popup-container.ts
- src/content/popup/popup.ts
- src/content/puck.ts
> fix: fix puck lookup stalling on iOS Safari

- CHANGELOG.md
- src/content/popup/words.ts
- src/utils/verb-tags.ts
> fix: prevent rendering of verb class tags on proverbs

- CHANGELOG.md
- src/background/deinflect.test.ts
- src/background/deinflect.ts
> feat: add irregular ta/te-stem for tamau/tamou

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- css/themes.css
- src/content/popup/KanjiReferencesTable.fixture.tsx
- src/content/popup/KanjiReferencesTable.tsx
- src/content/popup/popup.css
- src/content/popup/words.ts
> feat: link to WaniKani kanji and vocab pages

- src/background/deinflect.test.ts
- src/background/deinflect.ts
> fix: drop stem + suru rule

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/content/popup/words.ts
> feat: show search-only matches separately to entries

- knip.ts
- package.json
- yarn.lock
Updated Knip so we can see the React Cosmos plugin seems to do its job.
Let's wait with merging until the next version of Knip is published to npm.
> Update knip w/ react-cosmos plugin

- CHANGELOG.md
- manifest.json.src
- src/content/popup/KanjiReferencesTable.tsx
- src/content/popup/popup.css
- fix: drop use_dynamic_url from manifest
- fix: add underline offset for links
- chore: tweak CHANGELOG.md
> Various Chrome fixes

- CHANGELOG.md
- src/content/years.ts
> fix: don't match 0年

- CHANGELOG.md
- src/content/currency.test.ts
- src/content/currency.ts
- src/content/numbers.test.ts
- tests/get-text.test.ts
- tests/playground.html
> feat: add support for metric suffixes on currency values

- CHANGELOG.md
- src/common/config.ts
See https://bugs.webkit.org/show_bug.cgi?id=281644
Fixes #2045.
> fix: workaround Safari bug in reporting storage areaName

- CHANGELOG.md
- src/content/content.ts
- src/content/popup/render-popup.ts
- src/content/popup/tabs.ts
> fix: show metadata in the names tab when only names are available

- src/content/target-props.ts
- src/utils/char-range.ts
Fix a couple of issues that stopped the Enclosed Ideographic Supplement handling
from working correctly.
> fix enclosed ideographic supplement

- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_CN/messages.json
- package.json
- pnpm-lock.yaml
- src/content/copy-text.test.ts
- src/content/copy-text.ts
- src/content/popup/Kanji/KanjiComponents.fixture.tsx
- src/content/popup/Kanji/KanjiComponents.tsx
- src/content/popup/Kanji/KanjiEntry.fixture.tsx
- src/content/popup/Kanji/KanjiInfo.fixture.tsx
- src/content/popup/Kanji/KanjiInfo.tsx
- src/content/popup/Kanji/KanjiMeta.fixture.tsx
- src/content/popup/Kanji/KanjiReferencesTable.fixture.tsx
- src/content/popup/Kanji/KanjiReferencesTable.tsx
- src/content/reference-value.ts
- fix: set overhang on references table correctly
- feat: use v5 kanji data schema
> Update to v5 of kanji data schema

- package.json
- pnpm-lock.yaml
> chore: update react-cosmos-plugin-rspack to fix broken react-error-overlay

- CHANGELOG.md
- src/content/get-cursor-position.ts
- tests/get-text.test.ts
> feat: support Plex subtitles

- src/background/background.ts
- src/background/flat-file.ts
- src/background/word-search.ts
- src/common/config.ts
- src/content/content.ts
- src/content/popup/show-popup.ts
- src/content/query.ts
- src/utils/omit.ts
- chore: rename stripFields to omit
- chore: make omit return type distributive
- chore: use rest parameters in omit
> Tidy up stripFields/omit

- CHANGELOG.md
- src/content/get-cursor-position.ts
> fix: workaround Chromium buggy handling of multi-line textareas
