birchill/10ten-ja-reader

- __tests__/config.ts
- extension/options.html
- src/common.d.ts
- src/config.ts
- src/options.ts
- src/rikaicontent.ts
Fixes #5.
It worked before the custom keys commits happen (which then stuff explodes after rebasing and running `prepare`).
I couldn't run master either, so ┐(ಠ_ಠ)┌
```
src/config.ts(113,30): error TS2345: Argument of type '{ keys: KeyboardKeys; }' is not assignable to parameter of type 'StorageObject'.
Property 'keys' is incompatible with index signature.
Type 'KeyboardKeys' is not assignable to type 'StorageValue'.
Type 'KeyboardKeys' is not assignable to type 'StorageSet'.
Property '[Symbol.toStringTag]' is missing in type 'KeyboardKeys'.
```
> Add option to disable text highlighting

- src/content.ts
When I was visiting a website with body lang='zh-CN', I found that the rikaichamp popup window is also using the Chinese fontface, which is weird.
So I think it'll be nice to have a lang='ja-JP' for the popup.
> Add lang attribute to popup window

- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- changelog.md
- src/data.ts
- src/deinflect.test.ts
- src/deinflect.ts
issue #435 , like this: 美しきあの人. Technically it's not modern grammar but I think this is quite frequent.
BTW, I did nothing to the first two entries in `deinflectRuleData`; it's done automatically by the naughty `prettier --write`.
> Deinflect for i-adj ending in き preceding nouns

- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/popup.ts
They was displayed as-is, i.e. in English, and had a hardcoded `lang='en'`.
> Localize meta tags for kanji, i.e. 'kokuji' and 'phantom kanji'

- _locales/zh_hans/messages.json
The current translation of `obsc` itself seems 'obsc' to me.
Well, my own fault for copying the keys from Japanese locale :(
I suggest changing the translation in Japanese locale to `難解` also.
> Reconsider the meaning of "obsc" in Chinese translation

- .all-contributorsrc
https://github.com/all-contributors/all-contributors-cli/blob/f1a336d9f3e4a63c6ce69752ffa61d67e308fa4d/src/repo/index.js#L12
```
linkToCommits:
'<%= options.repoHost || "https://github.com" %>/<%= options.projectOwner %>/<%= options.projectName %>/commits?author=<%= contributor.login %>',
```
↑ According to this code, ```projectOwner``` need to be the github user name in order to form a valid link.
> Fix projectOwner for all-contributor

- xcode13/10ten Japanese Reader.xcodeproj/xcshareddata/xcschemes/10ten Japanese Reader (iOS).xcscheme
- xcode13/10ten Japanese Reader.xcodeproj/xcshareddata/xcschemes/10ten Japanese Reader (macOS).xcscheme
- xcode13/10ten Japanese Reader.xcodeproj/xcshareddata/xcschemes/10ten Japanese Reader Extension (iOS).xcscheme
- xcode13/10ten Japanese Reader.xcodeproj/xcshareddata/xcschemes/10ten Japanese Reader Extension (macOS).xcscheme
These let you run either the host app (as the default generated project allows you to) or the extension (in the context of Safari).
> chore: Xcode 13 run schemes

- CHANGELOG.md
- src/config.ts
Shift is not available when resist fingerprinting is enabled and Enter can be inconvenient.
Fixes #659.
> feat: Define an additional key for switching dictionaries

- src/puck.ts
Continuing from https://github.com/shirakaba/10ten-ja-reader/pull/16 (closed due to force-push).
I've refactored it into a state machine, though not completely sure I've followed your state flow. I ended up introducing intermediate states indicating whether a `pointerdown` event had been received on the puck (rather than some other element) prior to the `pointerup` (may be overcautious).
For discussion: do we prefer:
```ts
type ClickState =
| {
kind: 'idle';
}
| {
kind: 'gotpointerdown';
}
| {
kind: 'firstclick';
timeout: number;
}
| {
kind: 'firstclickwithpointerdown';
timeout: number;
};
```
... or:
```ts
type ClickState =
| {
kind: 'idle';
gotPointerDown: boolean;
}
| {
kind: 'firstclick';
gotPointerDown: boolean;
timeout: number;
};
```
I'm not too practised at modelling state …
> feat: flip moon orientation upon double-tap

- css/puck.css
- src/content.ts
- src/puck.ts
Upon a single-tap, the puck will remain draggable and responsive to single taps (and double taps, now that I think about it – I'm not too bothered about it either way) but importantly will stop looking up words.
https://user-images.githubusercontent.com/14055146/132957526-29ab97a7-6bc9-4aff-a540-d95808182e79.mp4
This allows you to dismiss the puck for a bit whilst trying to focus on the overall sentence, instead of having to find an adequate bit of whitespace to park it in.
> feat: toggle puck lookups upon single-tap

- CHANGELOG.md
- README.md
- src/worker/jpdict-worker-backend.ts
This was causing Firefox beta 111 to break since it starts parsing this
annotation and then failing when it is set.
Fixes #1080.
> fix: drop bogus { type: 'module' } from Worker instantiation

- CHANGELOG.md
- src/content/gdocs-canvas.ts
- src/content/get-cursor-position.ts
- src/content/get-text.ts
- src/content/scan-text.ts
- src/content/target-props.ts
- src/utils/dom-utils.ts
- src/utils/range.ts
- tests/get-text.test.ts
- tests/range.test.ts
Completely overhaul text lookup to cover more cases and be (hopefully) easier to
extend in future (so we can tackle #1130).
Fixes #990.
As mentioned in the discussion for #990, this has a negative performance impact
for most content. This is due to the extra distance calculations performed on
each lookup which is needed to avoid returning a cached position when the
distance has substantially changed.
For some content such as asahi.com, however, there is a net performance
improvement due to the way we handle repeated lookups.
For now this is probably acceptable, but if not, we will need to find a way to
cache the point used as input for the previous lookup and avoid doing distance
calculations if we determine we are close.
> fix: rewrite text scanning

- CHANGELOG.md
- CONTRIBUTING.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- css/options.css
- html/options.html
- html/options.html.src
- src/common/config.ts
- src/common/content-config-params.ts
- src/content/content-config.ts
- src/content/content.ts
- src/content/puck.ts
- src/content/touch-click-tracker.ts
- src/options/options.ts
- feat: add a setting to disable looking up words by tapping them
- fix: listen to pointermove events so we can ignore non-mouse events
- chore: add note about debugging on Fenix
> Add a setting to disable "tap to lookup"

- knip.ts
- package.json
- src/content/content.ts
- vitest.config.ts
- yarn.lock
As a follow-up to https://github.com/webpro/knip/issues/292, here's an updated Knip config:
- The Webpack plugin is now actually capable of finding those entry points that no longer need to be separately configured in `knip.ts`
- The Playwright plugin (or Knip itself) is not capable of using globs from `package.json#scripts` (yet)
- Removed a duplicate export (not sure why it wasn't reported before)
- Added this repo to https://github.com/webpro/knip/actions/workflows/integration.yml, so Knip runs against it to prevent regressions
- Should the Vitest config be updated to include the `scripts` dir?
The changes that unfortunately turned out breaking changes to a few repos were mostly caused by the fact that Knip no longer has a single glob for all test files, but the globs are moved to the …
> Upgrade knip and fix up config

- src/common/config.ts
- src/common/refs.ts
- src/content/copy-text.ts
- src/content/popup/kanji.ts
- src/content/reference-value.ts
- src/content/scan-text.ts
- src/options/CheckboxRow.tsx
- src/options/KanjiReferenceSetting.fixture.tsx
- src/options/KanjiReferenceSetting.tsx
- src/options/OptionsPage.tsx
- src/options/options.css
- src/options/options.html
- src/options/options.ts
- src/options/use-config-value.ts
- src/options/use-db.ts
- chore: fix typo
- chore: move database listening to a hook
- chore: convert dictionary data heading to Preact/Tailwind
- fix: expose the correct name for kanji references when reporting changes
- chore: move reference rendering to a separate file
- chore: remove dependency on browser polyfill from refs.ts
- chore: convert kanji reference setting UI to Preact
- chore: simplify useConfigValue
- chore: convert kanji reference settings styles to Tailwind
> Convert kanji reference settings to Preact/Tailwind

- .vscode/settings.json
- src/options/DbStatus.tsx
- src/options/KanjiReferenceSettings.fixture.tsx
- src/options/KanjiReferenceSettings.tsx
- src/options/KanjiReferenceSettingsForm.fixture.tsx
- src/options/KanjiReferenceSettingsForm.tsx
- src/options/OptionsPage.tsx
- src/options/SectionHeading.tsx
- src/options/tailwind.config.js
- chore: move SectionHeading to a separate file
- chore: rename KanjiReferenceSettingto KanjiReferenceSettings
- chore: move config bindings to separate wrapper
- chore: drop .vscode files
- chore: setup custom breakpoint for options screen
> Various tweaks to the options page

- _locales/zh_hans/messages.json
Some misc or field tags don't even have one entry associated, and I have no way to figure out their accurate meaning, so I left them as is. Apart from that, I think the translation looks pretty good now.
> Update zh-hans translation

- CHANGELOG.md
- src/content/currency.ts
- src/content/measure.ts
- src/content/meta.ts
- src/content/scan-text.ts
- src/content/shogi.ts
- src/content/years.ts
- src/utils/char-range.ts
- tests/get-text.test.ts
- tests/playground.html
As reported here:
https://github.com/birchill/10ten-ja-reader/issues/709#issuecomment-1764236624
> fix: recognize words that end in half-width numerals like 小1

- CHANGELOG.md
- src/common/config.ts
- src/content/content.ts
- fix: handle overlapping assignment of x key properly
- chore: add extension name to a few console messages
- fix: ignore redundant changes to canHover setting
> Fix overlapping assignment of 'x' key

- CHANGELOG.md
- src/content/popup/words.ts
- tests/playground.html
- fix: show direct matches on search-only headwords
- fix: hide "usually kana" annotation when there are no kanji
> Show search-only headwords when they are a direct match

- src/options/KanjiReferenceSettingsForm.tsx
- src/options/PopupInteractivitySettings.tsx
- src/options/PopupInteractivitySettingsForm.fixture.tsx
- src/options/PopupInteractivitySettingsForm.tsx
- src/options/options.css
- src/options/options.html
- src/options/options.ts
- src/utils/use-has-touch.ts
- chore: convert enable tap lookup setting to Preact/Tailwind
- fix: make double-clicking kanji reference labels not select the text
> Convert enable tap to lookup setting to Preact/Tailwind

- CHANGELOG.md
- src/content/puck.ts
See Codepen: https://codepen.io/birtles/pen/rNPKNQJ
In iOS Safari, if you call `preventDefault` on a `pointerdown` event you
will no longer get a subsequent `mousedown` / `mouseup`.
Calling `stopPropagation` appears to have no effect.
Conversely, in Chrome for Android, calling `stopPropagation` on a
`pointerdown` event will mean we no longer get a `mousedown` / `mouseup`
event but calling `preventDefault` will have no effect.
On Desktop it behaves the same as Safari.
Looks like Chrome for Android has a bug here for iframes however:
https://bugs.chromium.org/p/chromium/issues/detail?id=1016974
In Firefox for Android neither seems to have any effect. On Desktop, it
behaves the same as Safari.
I'll concede that this is the probably first time in history Safari for
iOS has actually done the …
> fix: ignore redundant mousedown/mouseup events on the puck

- CHANGELOG.md
- src/content/get-cursor-position.ts
- tests/get-text.test.ts
Minimal test case:
```html
<!doctype html>
<html>
<head>
<meta charset=utf-8>
<style type="text/css">
.container {
margin: 0 auto;
max-width: 1340px;
}
.textarea {
display: block;
width: 100%;
height: 300px;
}
</style>
</head>
<body>
<div class="container">
<textarea class="textarea">テスト</textarea>
</div>
</html>
```
As for the updated title for one of the existing test cases, this
hopefully reflects what it was originally introduced to test here:
https://github.com/birchill/10ten-ja-reader/commit/06797fa4c4673831707d53b089c13b45e220aad9
Fixes #1403.
> fix: check that the cursor is inside a textarea

- src/options/KeyboardSettings.tsx
- src/options/ToggleKeyForm.tsx
- fix: fix shortcut labels on Mac
- fix: make toggle key shortcut key wrap better
- fix: hide button to reset shortcut key when there's no API for it
- fix: show default shortcut key in more recent versions of Safari
> Various fixes to the Mac shortcut key setting

- CHANGELOG.md
- src/background/context-menus.ts
- src/background/fx-fetcher.ts
- src/background/jpdict-backend.ts
- src/options/use-db.ts
- fix: make currency fetching work in a service worker context
- fix: more robust handling of connection between options page and background page
- fix: handle contextMenus not being defined
- fix: apply objectStore.clear() workaround to Thunderbird too
> Various fixes to 1.16

- CHANGELOG.md
- src/background/all-tab-manager.ts
STR:
1. Start the add-on but don't enable it
2. Wait for the download to finish
3. Terminate the background process from about:debugging (or just wait
for it to terminate)
4. On any regular Web page, enable the add-on by clicking the icon on the
toolbar
Expected results:
The add-on is enabled immediately.
Actual results:
It takes two clicks.
Analysis:
We'd hit a race condition where we'd call tabManager.init() while the
tabManager was still being initialized. As a result it would update its
this.enabled member to `true` but then the initialization steps would
reset it back to false.
The fix is just to wait for the initialization to complete before trying
to toggle the value.
As far as I can tell this does not affect the ActiveTabManager because
its initialization is synchronous.
Fixes …
> fix: fix tab manager initialization race condition

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/content/popup/words.ts
In English we prefix the annotation with "from", e.g. "(from English)"
or "(from English: computer allergy)".
However, for wasei eigo we drop the "from", e.g. "(wasei English)".
We also indicate the source language for waseigo, e.g. "(wasei German:
Sack)".
We render wasei eigo as "wasei English" in the English localization
since some users will have an easier time parsing that than the more
common "wasei eigo" and anyone who understands "wasei eigo" will be able
to understand  "wasei English" too.
Some test cases I used for this:
- コンピューターアレルギー
- コンブリオ
- ナウ
- ゴータビリティー
- コンピュータマニア
- コンビナートキャンペーン
- サブザック
- シラー
Fixes #1468.
> feat: improve rendering of source language information

- CHANGELOG.md
- manifest.json.src
- src/content/gdocs-bootstrap.ts
Fixes #1529.
MV3 only allows the values "self", "wasm-unsafe-eval", and
"wasm-unsafe-eval" for an extension's `script-src` CSP setting.
As a result, we can no longer use inline script to update the main world
`window` global in order to enable Google Docs' annotated canvas mode.
Instead we use the new `world: 'MAIN'` setting and in Firefox, which
doesn't yet support that setting, we use Firefox's X-ray vision object
unwrapping.
Safari doesn't support Google Docs' annotated canvas due to:
https://bugs.webkit.org/show_bug.cgi?id=232781
However, Safari have indicated support for implementing `world: 'MAIN'`
in:
https://github.com/w3c/webextensions/issues/485
> fix: workaround MV3 CSP limitations in Google Docs bootstrap script

- src/background/background.ts
- src/common/config.ts
We've been getting an alarming number of AbortErrors being posted
recently but we have absolutely no context to work out where they are
coming from.
This patch adds some breadcrumbs to certain high-level operations in the
hope it helps to narrow down the cause of these errors.
Nothing is sent when there are no errors and input text is redacted when
it is sent.
> chore: add breadcrumbs for certain high-level operations

- src/background/fx-data.ts
- src/background/jpdict.ts
These happen a lot in Firefox and there doesn't seem to be anything we
can do about them short of retrying.
For now, notifying is just creating noise so we should log to the
console instead.
> chore: stop reporting common storage errors

- CHANGELOG.md
- src/content/popup/popup.ts
> fix: stop popup being inverted in Wikipedia's experimental dark mode

- CHANGELOG.md
- src/content/copy-text.ts
> fix: copy rare headwords when not in simplified copy mode

- src/content/content.ts
- src/utils/dom-utils.ts
Fixes #1654. Added in every interactive element I could think of, including contenteditable.
> feat: Ignore touch on more interactive elements

- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/options/DbStatus.tsx
> feat: add more helpful message when data storage is unavailable on Firefox

- .gitignore
- knip.ts
- src/common/i18n.polyfill.tsx
- src/common/i18n.tsx
- webpack.config.cosmos.js
- webpack.config.js
This will allow the production (browser API based) i18n provider to
render synchronously.
> chore: split i18n polyfill from production one

- package.json
- src/content/popup/KanjiReferencesTable.fixture.tsx
- src/content/popup/KanjiReferencesTable.tsx
- src/content/popup/cosmos.decorator.tsx
- src/content/popup/kanji.ts
This is nowhere near ready, just throwing it up as a draft for visibility, and as a place I can ask questions if I have them :).
Ignore the commit history, I plan to squash this down once it's ready to merge.
> Preactified popup

- src/content/popup/swipe.ts
I noticed scrolling on a touchscreen was not working on the newest `main`, then after a little investigation discovered this was (embarrassingly) introduced by my own tab swiping patch, and an overzealous `preventDefault()` call. Honestly, I'm not even sure why I had that in there to begin with...
Sure glad this hasn't been shipped yet! Sorry about that.
> bugfix: fix broken touch scrolling

- CONTRIBUTING.md
Just updating the `CONTRIBUTING.md` with some info that @shirakaba was good enough to [help me with a while back](https://github.com/birchill/10ten-ja-reader/pull/1656#issuecomment-2003394860). This is probably obvious to anyone who is a competent Apple developer, but was non-obvious to me, so I figure including might help someone else down the line.
> Update contribution guide with extra info about Xcode

- CHANGELOG.md
- src/background/jpdict.ts
Fixes https://github.com/birchill/10ten-ja-reader/issues/1205#issuecomment-1783641017.
**Side effects:** Combined characters like ㋿ will also be displayed as two separate kanji in the Kanji tab. Therefore there is a more consistent representation between the Word tab and the Kanji tab.
> fix: show kanji encoded as radicals in kanji tab

- src/background/deinflect.ts
This should not be possible, as Reason.None cannot stand on its own and needs a preceding rule to make sense.
This is a preventive measure, as this could lead to problems in the future if one rule being a subset of another rule in input as well as output is added, e.g. the rule
　たまう → 　たまう (te-form) being a subset of
のたまう → のたまう (te-form).
> fix: prevent starting a new reason chain with Reason.None

- CHANGELOG.md
- src/background/name-search.ts
- src/background/word-search.ts
> fix: fix duplicate matching of names with both 新字体 and 旧字体

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/common/config.ts
- src/common/content-config-params.ts
- src/content/content-config.ts
- src/content/content.ts
- src/content/measure.ts
- src/content/popup/metadata.test.ts
- src/content/popup/metadata.ts
- src/content/popup/names.ts
- src/content/popup/render-popup.ts
- src/content/popup/show-popup.ts
- src/content/popup/words.ts
- src/options/OptionsPage.tsx
- src/options/UnitSettings.tsx
- src/options/UnitSettingsForm.tsx
I will be the first person to admit that the imperial system is dumb, but it's what most Americans are accustomed to, and unfortunately I don't have an intuitive sense of how big a square meter is any more than I do 1畳, so hopefully this will be helpful to other SI-challenged folks like myself :).
It will still default to metric unless you set the setting to imperial.
@birtles and @SaltfishAmi, could use your help for the Japanese and Chinese l10ns if you don't mind (though in practice, I really doubt anybody will be using this in Chinese). Strings I need are:
`"metric"` — "メートル法" for Japanese?
`"imperial"` - "帝国単位" for Japanese?
`"Unit conversion"` (heading for the setting section with the drop down to select metric/imperial)
`"Preferred units"` (label on the drop down to select …
> feat: Add option to use imperial units when doing unit conversions

- CHANGELOG.md
- src/background/background.ts
- src/common/config.ts
We've received a report of the puck occasionally vanishing after
dragging on the Brave browser (desktop).
I finally worked out a reliable STR for this:
1. Enable the puck
2. Open a web page with a lot of white space and position the puck in
the white space.
3. Open the extensions management page in a separate window that you can
see side-by-side.
4. Wait for the service worker to go idle.
5. Move the puck within the white space and then release it.
Here's what happens:
1. The background service worker is suspended.
2. After dragging the puck, the content script dispatches a
"puckStateChanged" message to the background script.
3. The background service worker is woken up and immediately processes
the "puckStateChanged" message by executing:
```js
config.puckState = request.value
```
4. The …
> fix: fix puck vanishing after dragging

- src/background/deinflect.ts
The functionality previously handled by the VNai type is now fully represented by the irrealis stem intermediate type.
> chore: remove VNai intermediate type

- src/background/deinflect.ts
The contraction of せられる to される is incorrect for Ichidan verbs.
Related to #1849.
> fix: add される as inapplicable form for Ichidan verbs

- src/content/get-cursor-position.ts
> fix: don't use broken Blink implementation of caretPositionFromPoint

- CHANGELOG.md
- src/content/get-cursor-position.ts
- tests/get-text.test.ts
- tests/playground.html
The spec for caretPositionFromPoint has been updated to require
providing `shadowRoots` in order to dig into Shadow DOM content.[1]
This has been implemented in Chrome[2] and is due to ship in 128 (in beta
at the time of this patch).
It has also been implemented in Firefox[3] but is currently only enabled on
the Nightly channel.[4]
This API is quite annoying for extensions that simply want to scan all
the text in the document but I guess it makes sense for regular Web
apps.
[1] https://github.com/w3c/csswg-drafts/issues/9932
[2] https://issues.chromium.org/issues/41117286
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=1889503
[4] https://searchfox.org/mozilla-central/rev/64f196824745c5db5ef7bb23725cfb9a41586149/modules/libpref/init/StaticPrefList.yaml#4742-4751
> fix: pass in shadowRoots to caretPositionFromPoint

- src/content/popup/KanjiStrokeAnimation.tsx
This was supposed to be part of the original patch for the stroke
animation feature but we lost this commit when we rebased that branch.
> fix: work around Chrome path length bug

- scripts/zip-src.ts
We were asked to drop this as part of the Thunderbird add-on review
since the reviewer didn't want to review changes to the test files.
> chore: drop test files from src archive

- CHANGELOG.md
- src/content/touch-click-tracker.ts
Frequently the extension would have had to been disabled and re-enabled on mobile for taps to trigger the popup, this change is intended improve touch interaction reliability.
> Fix touch not triggering the popup when `body` is unavailable during init

- CHANGELOG.md
- src/background/word-match-sorting.ts
- fix: sort deinflected results by length
- fix: prioritize entries where most senses are "usually kana" when looking up by kana
> Various sorting fixes

- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_hans/messages.json
- src/content/popup/icons.ts
This is a really simple change, but I added tooltip text for when you hover over the filled/unfilled star, which will say "High priority entry" or "Priority entry", respectively. I thought this was worth adding because I was at one point minorly confused on what the stars meant, and what the difference between them was. Let me know if there are better labels to describe these.
I also added entries for the Japanese and Chinese localizations. The Chinese was machined translated and quite probably wrong. The Japanese was my best guess and also quite probably wrong 🙂.
> Add tooltip text for priority stars next to entries

- CHANGELOG.md
- src/background/deinflect.test.ts
- src/background/deinflect.ts
_Related to #1966._
Any reason chains containing duplicate reasons will now be discarded to avoid unreasonable matches.
> fix: prevent duplicate reasons in deinflection reason chains

- src/background/deinflect.test.ts
- src/background/deinflect.ts
_Follow-up to #2038._
I encountered duplicate results for inputs like 宣せぬ or 宣せず, which stemmed from the following rule:
```ts
['せる', 'する', Type.IchidanVerb, Type.SpecialSuruVerb, [Reason.Irregular, Reason.Potential]],
```
After reading again [this resource](https://www.edrdg.org/wwwjdic/wwwverbinf.html#suru_tag) from JMdict, I realized that this rule is incorrect. Verbs undergoing 五段化 have either し得る or できる as their potential forms, not the す-Godan potential form (せる).
By dropping this incorrect rule, the issue is resolved, and we can also revert the previous commit that was intended to prevent invalid sequencing of potential forms.
> Drop 五段化 potential rule

- src/background/deinflect.test.ts
- src/background/deinflect.ts
Follow-up to #2038.
This adds the 'negative -te' form of 五段化 verbs (e.g. 宣さないで), which I missed in the initial PR.
> fix: add 'negative -te' for 五段化 verbs

- src/content/popup/KanjiReferencesTable.tsx
This has been a problem starting from a while back on my iPhone mini screen: the kanji table overflows the x-axis.
Before:
With fix:
> Fix kanji references table overflow problem on small screens

- CHANGELOG.md
- src/content/popup/popup.css
- src/content/popup/render-popup.ts
- src/content/popup/show-popup.ts
- tests/popups.html
Fixes #2303.
Facebook defines it's only `--left` and `--top` properties like so:
```css
--left {
syntax: "*",
inherits: false,
}
```
Because `inherits` is false, the popup fails to pick up the `--left` and
`--top` values we set on the shadow container.
This patch adds a `tenten-` prefix to these properties to (hopefully)
avoid clashes.
> fix: namespace popup positioning properties

- CHANGELOG.md
- src/content/reference-value.ts
_Related to #2315._
With version 5 of the kanji data, the character is provided directly with no need for manual calculation from the radical number.
> fix: display correct Nelson radical information

- src/options/cosmos.decorator.tsx
- src/options/options.css
- src/options/options.ts
_Related to #2318._
Added the `options` CSS class to prevent style clashes when rendering popup content in React Cosmos, as currently `options.css` is being applied across all components viewed in React Cosmos.
This is a short-term measure. Solutions for a long-term fix are discussed in react-cosmos/react-cosmos#1638.
> fix: prevent style clashes in popup content fixtures in React Cosmos

- src/content/popup/Words/WordEntry.tsx
_Related to #2318._
_Fixes #2327._
It was erroneously dropped with the conversion of the words tab to Preact (5e24ba938a0dc1e1fba50bfa11c56cf15136a400).
> fix: re-add headword info to kana headwords

- CHANGELOG.md
- src/content/popup/popup.css
This fixes a bug where changing the font size in the settings wouldn't affect the kanji and names tabs.
> fix: fix Tailwind utility classes not reacting to the font size setting

- CHANGELOG.md
- _locales/en/messages.json
- _locales/ja/messages.json
- _locales/zh_CN/messages.json
- src/common/config.test.ts
- src/common/config.ts
- src/common/content-config-params.ts
- src/content/content.ts
- src/options/KeyboardSettings.tsx
- src/options/KeyboardSettingsForm.fixture.tsx
- src/options/KeyboardSettingsForm.tsx
- src/options/PopupKeysForm.tsx
- src/options/ShowPopupKeysForm.tsx
_Closes #2408, closes #1269._
This PR adds the option to use the Shift key to show the popup. However, this introduces a conflict with the `Switch dictionaries` and `Lookup kanji results only` options, as they also utilize the Shift key. In my opinion, the overlap with `Switch dictionaries` is not an issue and actually results in a convenient workflow for users who have Shift for hold to show activated  and frequently switch dictionaries.
To address the conflict with `Lookup kanji results only` it is automatically deactivated when the Shift key is set to `hold to show` and the option remains disabled as long as Shift is assigned for this.
I'm wondering whether we should allow users to choose a different key for `Lookup kanji results only`, so it would still be possible to activate it when …
> Add Shift as a possible keybinding for hold to show

- CHANGELOG.md
- src/content/popup/render-popup.ts
_Fixes #2457, fixes #2460._
Setting `tp:snap-y` and `tp:snap-mandatory` in `words.ts` is redundant and overrides the behavior in `expandable.ts`.
In Safari, this caused the Words list to scroll to random positions.
> fix: remove redundant snap settings causing random scroll jumps

- CHANGELOG.md
- src/content/content.ts
- src/content/get-cursor-position.ts
- src/content/get-text.ts
- src/content/scan-text.ts
- chore: rename lastMouseMove... to lastPointerMove...
- fix: catch pointermove events in the capture phase
- chore: use the actual start element when looking up target properties
> Update pointer move handling
